name: CI/CD Dev

on:
  push:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest
    name: Build and Test
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'
    - name: Run Tests
      run: 'npm run test'

  BuildLayer:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Build SLS Layer - Prod
    container:
      image: "node:14-buster"
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install --production
          mkdir nodejs
          mv node_modules nodejs
          apt update -y && apt install zip -y
          zip -r nodejs.zip nodejs/
      - uses: actions/upload-artifact@v2
        with:
          name: nodejsdeps
          path: nodejs.zip

  CD:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [CI, BuildLayer]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Load cached NPM dependencies
      id: cached-npm-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}
    - name: Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'
    - uses: actions/download-artifact@v2
      with:
        name: nodejsdeps
        path: app/
    - name: Deploy using sls
      run: 'npx sls deploy'
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
